#!/bin/bash
echo "=== Project Cleanup Report ==="
echo ""
echo "🗑️  Cleanable Items:"
echo ""
echo "node_modules size: $(du -sh node_modules 2>/dev/null | cut -f1 || echo 'Not found')"
echo ".next build size: $(du -sh .next 2>/dev/null | cut -f1 || echo 'Not found')"
echo ".turbo cache: $(du -sh .turbo 2>/dev/null | cut -f1 || echo 'Not found')"
echo ""
echo "📊 Temporary files:"
echo "  Log files: $(find . -name '*.log' 2>/dev/null | wc -l)"
echo "  Temp files: $(find . -name '*.tmp' 2>/dev/null | wc -l)"
echo "  DS_Store: $(find . -name '.DS_Store' 2>/dev/null | wc -l)"
echo ""
echo "💡 To clean, run:"
echo "  rm -rf node_modules .next .turbo"
echo "  npm install"
echo ""
echo "⚠️  Note: This is a dry-run. No files were deleted."
