#!/bin/bash
echo "=== Environment Check ==="
echo ""
echo "🔧 System Info:"
echo "  OS: $(uname -s)"
echo "  Architecture: $(uname -m)"
echo "  Kernel: $(uname -r)"
echo ""
echo "🛠️  Development Tools:"
echo "  Node.js: $(node --version 2>/dev/null || echo 'Not installed')"
echo "  npm: $(npm --version 2>/dev/null || echo 'Not installed')"
echo "  Git: $(git --version 2>/dev/null | cut -d' ' -f3 || echo 'Not installed')"
echo ""
echo "📦 Next.js:"
npm list next 2>/dev/null | grep next@ || echo "  Not found"
echo ""
echo "🌍 Environment Variables:"
env | grep NEXT_PUBLIC | head -10 || echo "  No NEXT_PUBLIC variables found"
echo ""
echo "💻 Current Shell: $SHELL"
echo "👤 Current User: $(whoami)"
