#!/bin/bash
echo "=== Git Status Report ==="
echo ""
echo "Current branch: $(git branch --show-current 2>/dev/null || echo 'Not a git repository')"
echo "Remote: $(git remote get-url origin 2>/dev/null || echo 'No remote configured')"
echo ""
echo "Recent commits:"
git log --oneline -5 2>/dev/null || echo "No commits found"
echo ""
echo "Modified files:"
git status --short 2>/dev/null || echo "No changes"
echo ""
echo "Stashed changes: $(git stash list | wc -l)"
echo "Untracked files: $(git ls-files --others --exclude-standard | wc -l)"
