#!/bin/bash
echo "=== Project Statistics ==="
echo ""
echo "📁 Project: $(basename $(pwd))"
echo "📅 Date: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "📊 File Counts:"
echo "  TypeScript files: $(find app -name '*.ts' -o -name '*.tsx' 2>/dev/null | wc -l)"
echo "  JavaScript files: $(find app -name '*.js' -o -name '*.jsx' 2>/dev/null | wc -l)"
echo "  API Routes: $(find app/api -name 'route.ts' 2>/dev/null | wc -l)"
echo "  Components: $(find app -name '*.tsx' 2>/dev/null | wc -l)"
echo ""
echo "📝 Lines of Code:"
find app -name '*.ts' -o -name '*.tsx' 2>/dev/null | xargs wc -l 2>/dev/null | tail -1 || echo "  Unable to count"
echo ""
echo "📦 Dependencies:"
echo "  Production: $(cat package.json | grep -c '"' | head -1)"
echo "  Dev: $(cat package.json | grep devDependencies -A 50 | grep -c '"')"
echo ""
echo "💾 Storage:"
echo "  Total project: $(du -sh . 2>/dev/null | cut -f1)"
echo "  node_modules: $(du -sh node_modules 2>/dev/null | cut -f1 || echo 'Not found')"
echo "  .next build: $(du -sh .next 2>/dev/null | cut -f1 || echo 'Not found')"
